# @package _global_

defaults:
  - static
  - override /data_loaders:
      - infer_static
      - live
  - override /data_source:
      - infer_static
      - live

infer:
  frequency: 0
  frequency_inner: 20
  rollout_wait: input
  # start_rollout: 18
interactor:
  action_from: data_loader
