# @package _global_

infer:
  frequency: -1
  rollout_wait: null
interactor:
  _target_: configs.inter.Interactor
  extractor:
    model_path: "pretrained_models/blip2-itm-vit-g"
    prompt: The end effector of the robotic arm tries to get close to the QR code attached to the cabinet
    enable: false
    keys_from:
      - 0${extra.env_color}
  open_loop_predict: false
  action_from: none
  model_input_from: data_loader
stage: infer
