# @package _global_

defaults:
  - basis

infer:
  frequency: 0
  rollout_wait: input

interactor:
  extractor:
    enable: true
  open_loop_predict: true
  action_from: model
  model_input_from: env
