# @package _global_

defaults:
  - /data_loaders: train_val
  - /data_source: train_val

train:
  iteration:
    max_train_time: 10 # minutes
    patience: 250 # epochs
    max_epoch: 1000
    min_val_loss: 0.00045
    min_train_time: 10
  snapshot:
    - keys: ["train_loss", "val_loss", "min_train_loss", "min_val_loss"]
      interval: 1
stage: train
