# @package data_loaders.sources.live.source

defaults:
  - live

components:
  instances:
    - _target_: airbot_ie.robots.airbot_play_mock.AIRBOTPlay
    - _target_: airbot_data_collection.common.devices.cameras.mock.MockCamera
