# @package _global_

defaults:
  - single@extra

extra:
  root: logs/checkpoints
  arm_state: /follow/arm/joint_state/position
  eef_state: /follow/eef/joint_state/position
  action_keys:
    - ${extra.env_color_feat}
model:
  _target_: models.multimodel.MultiModel
  callables:
    - ${extra.model}
    - ${extra.model}
  paths:
    - ${extra.root}/0
    - ${extra.root}/1
data_loader:
  horizon:
    past_num: 0
    future_num: 0
    gap: 1
    fill_with_last: true
  stack:
    cur_state:
      - 0.0${extra.arm_state}
      # - 0.0${extra.eef_state}
    cur_action:
      - ["${extra.action_keys}", [1.0, 1.5]]
    next_action:
      - ["${extra.action_keys}", [1.0, 1.5]]
