# @package _global_

defaults:
  - basis@extra.model_config
  - loader

model:
  _target_: configs.models.multimodel.MultiModel
  callables:
    - _target_: models.deep_koopman.DeepKoopman
      config: ${extra.model_config}
  axis: 1 # concat axis alone the T dimension
