# @package _global_

model:
  _target_: models.deep_koopman.DeepKoopman
  config:
    _target_: models.deep_koopman.DeepKoopmanConfig
    hidden_sizes:
      - 512
      - 512
      - 512
    lifted_dim: 256

data_loader:
  pairwise:
    gap: 0
    fill_with_last: true
  stack:
    cur_state:
      - 0${extra.arm_state}
      # - 0.0${extra.eef_state}
    cur_action:
      - 0${extra.env_color_feat}
    next_state:
      - 1${extra.arm_state}
