# @package _global_

model:
  _target_: models.deep_koopman.DeepKoopman
  config:
    _target_: models.deep_koopman.DeepKoopmanConfig
    hidden_sizes:
      - 512
      - 512
      - 512
    lifted_dim: 256
data_loader:
  pair_gap: 0
