# @package _global_

extra:
  arm_state: /follow/arm/joint_state/position
  eef_state: /follow/eef/joint_state/position
  env_color: /env_camera/color/image_raw
  env_color_feat: ${extra.env_color}/features_proj
  follow_color: /follow_camera/color/image_raw
  follow_color_feat: ${extra.follow_color}/features_proj
  image_keys:
    - ${extra.env_color}
    - ${extra.follow_color}
  cur_state:
    - ${extra.arm_state}
    # - ${extra.eef_state}
  cur_action:
    - ${extra.env_color_feat}
    - ${extra.follow_color_feat}
  next_state:
    - 1${extra.arm_state}
    # - 1${extra.eef_state}
