defaults:
  - _self_
  - model: single
  # - infer: test_single # use +infer=test_single in CLI

extra:
  arm_state: /follow/arm/joint_state/position
  eef_state: /follow/eef/joint_state/position
  env_color: /env_camera/color/image_raw
  env_color_feat: ${extra.env_color}/features_proj

datasets:
  _target_: configs.data.get_datasets
  data_name: reach3tags
data_loader:
  # _target_: configs.data.get_data_loader_config
  batch_size: 64
  dict_tuple:
    depth: 2
    separator: "."
    separate_key: false
  parallel:
    num_workers: 0
    snapshot_frequency: 1000
train:
  iteration:
    max_train_time: 20 # minutes
    patience: 250 # epochs
    max_epoch: 5000
    min_val_loss: 0.00045
    min_train_time: 20
  snapshot:
    - keys: ["train_loss", "val_loss", "min_train_loss", "min_val_loss"]
      interval: 1
  train_val_split: [2, 1]
loss_fn:
  _target_: configs.data.LossCalculator
